version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_USER=your-rds-username
      - DB_PASS=your-rds-password
      - DB_NAME=cakershop
